language: php
php:
  - '7.2'
services:
  - 'mysql'  
before_script:
  - composer self-update
  - composer install --no-interaction
  - mysql -u root --password="" -e "CREATE DATABASE mazaad"
  - cp .env.travis .env
  
